// ── Trash Categories & Items ──
// Each category has: name (display), icon (emoji), cls (CSS class), tip (shown on mistakes), color (effects), items array.
// Items may carry their own tip for common sorting traps; it replaces the bin tip on mistakes.

export const CATEGORIES = {
  gelb: {
    name: 'Gelbe Tonne',
    icon: '♻️',
    cls: 'bin-gelb',
    tip: 'Verpackungen aus Plastik, Metall und Getränkekartons – leer, nicht gespült.',
    color: '#ffd23f',
    items: [
      { emoji: '🛍️', name: 'Plastiktüte' },
      { emoji: '🧴', name: 'Shampooflasche' },
      { emoji: '🥤', name: 'Plastikbecher' },
      { emoji: '🥫', name: 'Konservendose' },
      { emoji: '🍫', name: 'Schokopack' },
      { emoji: '🧃', name: 'Getränkekarton' },
      { emoji: '🥛', name: 'Milchkarton', tip: 'Getränkekartons sind Verbundverpackung – Gelbe Tonne, nicht Papier.' },
      { emoji: '🧈', name: 'Butterfolie', tip: 'Butterfolie aus Alu-Papier-Verbund ist Verpackung – Gelbe Tonne.' },
      { emoji: '🍨', name: 'Eisbecher' },
      { emoji: '🍬', name: 'Bonbonpapier', tip: 'Bonbonpapier ist eine Plastikverpackung – Gelbe Tonne.' },
    ],
  },
  glas: {
    name: 'Glascontainer',
    icon: '🍾',
    cls: 'bin-glas',
    tip: 'Nur Flaschen und Gläser – Trinkgläser und Glühbirnen gehören in den Restmüll.',
    color: '#2fcf74',
    items: [
      { emoji: '🍾', name: 'Sektflasche' },
      { emoji: '🫙', name: 'Marmeladenglas' },
      { emoji: '🍶', name: 'Glasflasche' },
      { emoji: '🧂', name: 'Gewürzglas' },
      { emoji: '🫗', name: 'Saftflasche' },
      { emoji: '🍯', name: 'Honigglas' },
      { emoji: '🫒', name: 'Olivenglas' },
    ],
  },
  papier: {
    name: 'Papiertonne',
    icon: '📦',
    cls: 'bin-papier',
    tip: 'Papier, Pappe und Kartons – fettige Pizzakartons aber in den Restmüll.',
    color: '#3d8bff',
    items: [
      { emoji: '📰', name: 'Zeitung' },
      { emoji: '📦', name: 'Karton' },
      { emoji: '📚', name: 'Alte Bücher' },
      { emoji: '🗞️', name: 'Zeitschrift' },
      { emoji: '✉️', name: 'Briefumschlag' },
      { emoji: '🗒️', name: 'Notizheft' },
      { emoji: '📄', name: 'Prospekt' },
      { emoji: '🎁', name: 'Geschenkpapier' },
      { emoji: '🗓️', name: 'Alter Kalender' },
      { emoji: '🧻', name: 'Klopapierrolle (leer)', tip: 'Die leere Papprolle ist Pappe – Papiertonne.' },
    ],
  },
  bio: {
    name: 'Biotonne',
    icon: '🌱',
    cls: 'bin-bio',
    tip: 'Obst-, Gemüse- und Gartenreste, Kaffeesatz und Eierschalen.',
    color: '#b9793d',
    items: [
      { emoji: '🍌', name: 'Bananenschale' },
      { emoji: '🥚', name: 'Eierschale' },
      { emoji: '☕', name: 'Kaffeesatz' },
      { emoji: '🍎', name: 'Apfelrest' },
      { emoji: '🌿', name: 'Gartenabfall' },
      { emoji: '🥕', name: 'Gemüsereste' },
      { emoji: '🍞', name: 'Altbrot' },
      { emoji: '🍂', name: 'Laub' },
      { emoji: '🥔', name: 'Kartoffelschalen' },
      { emoji: '🍵', name: 'Teebeutel', tip: 'Teebeutel samt Papierhülle dürfen in die Biotonne.' },
      { emoji: '💐', name: 'Schnittblumen' },
      { emoji: '🍋', name: 'Zitronenschale' },
    ],
  },
  rest: {
    name: 'Restmüll',
    icon: '🗑️',
    cls: 'bin-rest',
    tip: 'Was nicht verwertbar ist: Hygieneartikel, Kehricht, kaputtes Trinkglas.',
    color: '#9aa6b8',
    items: [
      { emoji: '🍕', name: 'Pizzakarton (fettig)', tip: 'Fettige Pizzakartons – Restmüll. Nur saubere Pappe gehört ins Papier.' },
      { emoji: '💡', name: 'Glühbirne', tip: 'Alte Glühbirnen – Restmüll. Energiespar- und LED-Lampen – Sondermüll.' },
      { emoji: '🩹', name: 'Pflaster' },
      { emoji: '🧼', name: 'Seifenreste' },
      { emoji: '🖊️', name: 'Kugelschreiber' },
      { emoji: '🪥', name: 'Zahnbürste' },
      { emoji: '🥂', name: 'Trinkglas (kaputt)', tip: 'Trinkgläser schmelzen anders als Flaschenglas – Restmüll, nie Glascontainer.' },
      { emoji: '🪣', name: 'Kunststoffeimer', tip: 'Die Gelbe Tonne ist nur für Verpackungen – ein Eimer ist keine. Restmüll oder Wertstoffhof.' },
      { emoji: '🧾', name: 'Kassenbon', tip: 'Kassenbons sind Thermopapier – Restmüll, nicht Papiertonne.' },
      { emoji: '🪞', name: 'Spiegel', tip: 'Spiegelglas ist beschichtet – Restmüll, nie Glascontainer.' },
      { emoji: '🫖', name: 'Keramik-Teekanne', tip: 'Keramik und Porzellan gehören in den Restmüll, nicht zum Glas.' },
      { emoji: '🚬', name: 'Zigarettenstummel' },
      { emoji: '🕯️', name: 'Kerzenreste' },
      { emoji: '🐈', name: 'Katzenstreu', tip: 'Katzenstreu – auch „kompostierbare“ – gehört in den Restmüll.' },
      { emoji: '📸', name: 'Alte Fotos', tip: 'Fotopapier ist beschichtet – Restmüll, nicht Papier.' },
    ],
  },
  sonder: {
    name: 'Sondermüll',
    icon: '☢️',
    cls: 'bin-sonder',
    tip: 'Batterien, Chemikalien, Elektroschrott – zum Wertstoffhof, nie in den Hausmüll.',
    color: '#ff4d5e',
    items: [
      { emoji: '🔋', name: 'Batterie' },
      { emoji: '🎨', name: 'Lackreste' },
      { emoji: '💊', name: 'Medikamente' },
      { emoji: '🧪', name: 'Chemikalien' },
      { emoji: '🖨️', name: 'Druckerpatronen' },
      { emoji: '📱', name: 'Altes Handy' },
      { emoji: '💻', name: 'Elektroschrott' },
      { emoji: '🛢️', name: 'Altöl' },
      { emoji: '🌡️', name: 'Quecksilber-Thermometer' },
      { emoji: '💅', name: 'Nagellack' },
      { emoji: '🧯', name: 'Feuerlöscher' },
    ],
  },
};

export const CAT_KEYS = Object.keys(CATEGORIES);
